#!/bin/bash
#
# Плагин для мониторинга DUR

HOST=lord.rmart.ru
DB=wormswar_mobile
USER=smos

if [ "$1" = "config" ]; then
    echo 'graph_title Daily User Registrations Stat'
    echo 'graph_vlabel count'
    echo 'graph_args -l 0'
    echo 'graph_noscale true'
    echo 'graph_category Wormix iOS Stat'
    echo 'graph_info Daily User Registrations on Wormix iOS'

    echo 'dur.label dur'
    echo 'dur.info DUR'
    echo 'dur.min 0'

    echo 'tur.label tur'
    echo 'tur.info Today User Registrations'
    echo 'tur.min 0'
    exit 0
fi

echo -n "dur.value"
echo "select count(id) from wormswar.creation_date where creation_date > now() - interval '24 hours'" | psql -h $HOST -d $DB -U $USER -t

echo -n "tur.value"
echo "select count(id) from wormswar.creation_date where creation_date > 'TODAY'" | psql -h $HOST -d $DB -U $USER -t
