#!/bin/sh
#
# Плагин для мониторинга PVP коннекта

StatDump=/home/user/server_pvp/logs/statistics/stat.dump

if [ "$1" = "config" ]; then
    echo 'graph_title Wormix Server (PVP Battles #2)'
    echo 'graph_vlabel pvp_battles'
    echo 'graph_noscale true'
    echo 'graph_category Wormix'
    echo 'graph_info This graph shows statistics about Wormix Server (PVP Battles)'


    echo 'friend_pve.label PvE_FRIEND'
    echo 'friend_pve.info PvE_FRIEND'

    echo 'partner_pve.label PvE_PARTNER'
    echo 'partner_pve.info PvE_PARTNER'

    echo 'wager_duel_300.label WAGER_PvP_DUEL_300'
    echo 'wager_duel_300.info WAGER_PvP_DUEL 300'

    exit 0
fi

echo -n "friend_pve.value "
cat $StatDump | grep "^pvp:PvE_FRIEND" | awk '{print $3}'
echo -n "partner_pve.value "
cat $StatDump | grep "^pvp:PvE_PARTNER" | awk '{print $3}'
echo -n "wager_duel_300.value "
cat $StatDump | grep "^pvp:WAGER_PvP_DUEL_300" | awk '{print $3}'
