#!/bin/sh
#
# Плагин для мониторинга PVP коннекта

StatDump=/home/user/server_pvp/logs/statistics/stat.dump

if [ "$1" = "config" ]; then
    echo 'graph_title Wormix Server (PVP Battles)'
    echo 'graph_vlabel pvp_battles'
    echo 'graph_noscale true'
    echo 'graph_category Wormix'
    echo 'graph_info This graph shows statistics about Wormix Server (PVP Battles)'


    echo 'wager_duel_15.label WAGER_PvP_DUEL_15'
    echo 'wager_duel_15.info WAGER_PvP_DUEL 15'

    echo 'wager_duel_0.label PvP_GLADIATOR_DUEL'
    echo 'wager_duel_0.info PvP_GLADIATOR_DUEL'

    echo 'mercenaries_duel.label PvP_MERCENARIES_DUEL'
    echo 'mercenaries_duel.info PvP_MERCENARIES_DUEL'

    echo 'wager_3_for_all.label WAGER_PvP_3_FOR_ALL'
    echo 'wager_3_for_all.info WAGER_PvP_3_FOR_ALL'

    echo 'friend_pve.label PvE_FRIEND'
    echo 'friend_pve.info PvE_FRIEND'

    echo 'friend_pvp.label FRIEND_PvP'
    echo 'friend_pvp.info FRIEND_PvP'

    echo 'partner_pve.label PvE_PARTNER'
    echo 'partner_pve.info PvE_PARTNER'

    echo 'wager_2x2.label WAGER_PvP_2x2'
    echo 'wager_2x2.info WAGER_PvP_2x2'

    echo 'wager_duel_300.label WAGER_PvP_DUEL_300'
    echo 'wager_duel_300.info WAGER_PvP_DUEL 300'

    echo 'quest_duel.label QUEST_DUEL'
    echo 'quest_duel.info QUEST DUEL'

    echo 'wager_duel_20.label WAGER_PvP_DUEL_20'
    echo 'wager_duel_20.info WAGER_PvP_DUEL 20'

    exit 0
fi

echo -n "friend_pvp.value "
cat $StatDump | grep "^pvp:FRIEND_PvP" | awk '{print $3}'
echo -n "friend_pve.value "
cat $StatDump | grep "^pvp:PvE_FRIEND" | awk '{print $3}'
echo -n "partner_pve.value "
cat $StatDump | grep "^pvp:PvE_PARTNER" | awk '{print $3}'
echo -n "wager_2x2.value "
cat $StatDump | grep "^pvp:WAGER_PvP_2x2" | tail -1 | awk '{print $3}'
echo -n "wager_3_for_all.value "
cat $StatDump | grep "^pvp:WAGER_PvP_3_FOR_ALL" | awk '{print $3}'
echo -n "wager_duel_15.value "
cat $StatDump | grep "^pvp:WAGER_PvP_DUEL_15" | awk '{print $3}'
echo -n "wager_duel_300.value "
cat $StatDump | grep "^pvp:WAGER_PvP_DUEL_300" | awk '{print $3}'
echo -n "wager_duel_0.value "
cat $StatDump | grep "^pvp:GLADIATOR_DUEL" | awk '{print $3}'
echo -n "quest_duel.value "
cat $StatDump | grep "^pvp:QUEST_DUEL" | awk '{print $3}'
echo -n "mercenaries_duel.value "
cat $StatDump | grep "^pvp:MERCENARIES_DUEL" | awk '{print $3}'
echo -n "wager_duel_20.value "
cat $StatDump | grep "^pvp:WAGER_PvP_DUEL_20" | awk '{print $3}'
