#!/bin/sh
#
# Плагин для мониторинга статистики AuthTaskExecutor

StatDump=/home/user/server/logs/statistics/stat.dump

if [ "$1" = "config" ]; then
    echo 'graph_title Wormix Main Server (AuthTaskExecutor)'
    echo 'graph_vlabel main_AuthTaskExecutor'
    echo 'graph_noscale true'
    echo 'graph_category Wormix VK Main'
    echo 'graph_info This graph shows statistics about Wormix Main Server (AuthTaskExecutor)'

    echo 'queueLength_avg.label queueLengthAvg'
    echo 'queueLength_avg.info Queue length AVG'

    echo 'queueLength_max.label queueLengthMax'
    echo 'queueLength_max.info Queue length MAX'

    echo 'taskProcessTime.label taskProcessTime'
    echo 'taskProcessTime.info Task process time AVG'

    echo 'taskWaitInQueueTime.label taskWaitInQueueTime'
    echo 'taskWaitInQueueTime.info Task wait in queue time AVG'

    exit 0
fi

echo -n "queueLength_avg.value "
cat $StatDump | grep "AuthExec:queueLength" | awk '{print $3}'
echo -n "queueLength_max.value "
cat $StatDump | grep "AuthExec:queueLength" | awk '{print $4}'
echo -n "taskProcessTime.value "
cat $StatDump | grep "AuthExec:taskProcessTime" | awk '{print $3}'
echo -n "taskWaitInQueueTime.value "
cat $StatDump | grep "AuthExec:taskWaitInQueueTime" | awk '{print $3}'
