[
        "server.getContext"                        : ["server", "getContext", false],
        "server.getBanStatistic"                   : ["server", "getBanStatistic", false],
        "server.getOnline"                         : ["server", "getOnline", false],
        "server.refreshContext"                    : ["server", "refreshContext", false],
        "server.bonus.get"                         : ["server", "getBonusDays", false],
        "server.bonus.set"                         : ["server", "setBonusDays", true],
        "server.appParams.get"                     : ["server", "getAppParams", false],
        "server.appParams.set"                     : ["server", "setAppParams", true],
        "server.referralLinks.get"                 : ["server_maintenance", "getReferralLinks", false],
        "server.referralLinks.new"                 : ["server_maintenance", "newReferralLink", true],
        "server.referralLinks.remove"              : ["server_maintenance", "removeReferralLink", true],
        "server.bundles.get"                       : ["server_maintenance", "getBundles", false],
        "server.bundles.persist"                   : ["server_maintenance", "persistBundle", true],
        "server.mercenaries.get"                   : ["server_maintenance", "getMercenariesDefs", false],
        "server.mercenaries.update"                : ["server_maintenance", "updateMercenaryDef", true],

        "gamer.view"                               : ["gamer_view", "getUserProfile", false],
        "gamer.view.awards"                        : ["gamer_view", "getAwardStatistic", false],
        "gamer.view.payments"                      : ["gamer_view", "getPaymentStatistic", false],
        "gamer.view.purchases"                     : ["gamer_view", "getShopStatistic", false],
        "gamer.view.battles"                       : ["gamer_view", "getBattleStatistic", false],
        "gamer.view.battlesDetails"                : ["gamer_view", "getPvpBattlesDetails", false],
        "gamer.view.bossBattles"                   : ["gamer_view", "getBossBattleStatistic", false],
        "gamer.view.achievements"                  : ["gamer_view", "getAchievements", false],
        "gamer.view.blackList"                     : ["gamer_view", "getBlackList", false],
        "gamer.batchView"                          : ["gamer_batch", "batchView", false],
        "gamer.batchSearch"                        : ["common", "findByName", false],
        "gamer.batchClearName"                     : ["gamer_batch", "batchClearName", true],

        "gamer.ban"                                : ["gamer_ban", "banProfile", false],
        "gamer.unban"                              : ["gamer_ban", "unbanProfile", false],
        "gamer.batchBan"                           : ["gamer_ban", "batchBan", false],
        "gamer.batchUnban"                         : ["gamer_ban", "batchUnban", false],
        "gamer.restrict.view"                      : ["gamer_ban", "getRestrictionsHistory", false],
        "gamer.restrict.add"                       : ["gamer_ban", "addRestriction", false],
        "gamer.restrict.edit"                      : ["gamer_ban", "editRestriction", false],
        "gamer.batchRestrict"                      : ["gamer_batch", "addRestriction", false],

        "gamer.grantAward"                         : ["gamer_update", "grantAward", true],
        "gamer.update"                             : ["gamer_update", "update", true],
        "gamer.update.weapon"                      : ["gamer_update", "updateWeapon", true],
        "gamer.update.stuff"                       : ["gamer_update", "updateStuff", true],
        "gamer.update.achievements"                : ["gamer_update", "updateAchievements", true],
        "gamer.update.reagents"                    : ["gamer_update", "updateReagents", true],
        "gamer.update.weapon.cleanBackpack"        : ["gamer_update", "cleanBackpack", true],
        "gamer.update.weapon.downgradeAll"         : ["gamer_update", "downgradeAll", true],
        "gamer.update.cleanPaymetsStat"            : ["gamer_update", "cleanPaymetsStat", true],
        "gamer.update.deposit"                     : ["gamer_update", "updateDeposit", true],

        "gamer.utils.kickOut"                      : ["gamer_utils", "kickOut", true],
        "gamer.utils.wipeProfile"                  : ["gamer_utils", "wipeProfile", true],
        "gamer.utils.clearCache"                   : ["gamer_utils", "clearCache", false],
        "gamer.utils.sendMessage"                  : ["gamer_utils", "sendMessage", false],
        "gamer.utils.clearMission"                 : ["gamer_utils", "clearMission", true],
        "gamer.utils.resetMissions"                : ["gamer_utils", "resetMissions", true],

        "server.onlineManagement.kickOutAll"       : ["server_maintenance", "kickOutAll", true],
        "server.onlineManagement.admitAll"         : ["server_maintenance", "admitAll", true],
        "server.onlineManagement.broadcast"        : ["server_maintenance", "broadcast", true],
        "server.getTop"                            : ["server_maintenance", "getTop", false],
        "server.getClanTop"                        : ["server_maintenance", "getClanTop", false],
        "server.getPairTop"                        : ["server_maintenance", "getPairTop", false],
        "server.getOnlineProfiles"                 : ["server_maintenance", "getOnlineProfiles", false],
        "server.desynchView"                       : ["gamer_batch", "desynchView", false],
        "server.desynchViewFillProfiles"           : ["gamer_batch", "desynchViewFillProfiles", false],
        "server.bossCheatStats"                    : ["gamer_batch", "getBossCheatStats", false],
        "server.pvpCheatStats"                     : ["gamer_batch", "getPvpCheatStats", false],
        "server.getTopDonaters"                    : ["server_maintenance", "getTopDonaters", true],
        "server.getTesters"                        : ["server_maintenance", "getTesters", false],
        "server.setTesters"                        : ["server_maintenance", "setTesters", true],
        "server.sendVkActiveGamers"                : ["server_maintenance", "sendVkActiveGamers", false],
        "server.superBossDailyStat"                : ["server_maintenance", "superBossDailyStat", false],
        "server.setSuperBossLevel"                 : ["server_maintenance", "setSuperBossLevel", false],
        "server.getGlobalChatHistory"              : ["server_maintenance", "getGlobalChatHistory", false],
        "server.removeMessageFromGlobalChatHistory": ["server_maintenance", "removeMessageFromGlobalChatHistory", true],

        "server.shiftHeroicMission"                : ["server_utils", "shiftHeroicMission", true],
        "server.callMethod"                        : ["server_utils", "callMethod", true],
        "server.runDailyTask"                      : ["server_utils", "runDailyTask", true],
        "server.getBlackListTop"                   : ["server_utils", "getBlackListTop", false],

        "server.callChiefMethod"                   : ["chief_utils", "callMethod", true],

        "clan.list"                                : ["clan", "getClanList", false],
        "clan.view"                                : ["clan", "getClan", false],
        "clan.getActions"                          : ["clan", "getActions", false],
        "clan.update"                              : ["clan", "updateClan", true],
        "clan.lock"                                : ["clan", "lockClan", true],
        "clan.approveAll"                          : ["clan", "approveAll", true],
        "clan.member.add"                          : ["clan", "add", true],
        "clan.member.expel"                        : ["clan", "expel", true],
        "clan.member.setRank"                      : ["clan", "setRank", true],
        "clan.member.expelPermit"                  : ["clan", "expelPermit", true],

        "server.bossBattleStats"                   : ["common", "bossBattleStats", false],
        "server.bossBattleExtraReward.get"         : ["common", "bossBattleExtraReward", false],
        "server.bossBattleExtraReward.modify"      : ["common", "bossBattleExtraReward", true],
        "gamer.update.removeFromGroup"             : ["common", "removeFromGroup", true],
        "server.shiftHeroicMissionsState"          : ["common", "shiftHeroicMissionsState", true],
]